### ISSUE TITLE
Cannot find module 'react-gridsheet' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by righ** [codesandbox/codesandbox-client#5452]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

  - I think this is the similar to #4828, #5191, but these did not help me in my case.

## Description of the problem
Type resolution has not been working since `react-gridsheet@0.2.13`. (work well in 0.2.12)

`Cannot find module 'react-gridsheet' or its corresponding type declarations.ts(2307)`

The diff between 0.2.12 and 0.2.13 is following. But that does not contain tsconfig and package.json and so on.
https://github.com/walkframe/react-gridsheet/commit/f8a2eb602c5f9d48efac506e2f91f512b4bcad

FYI this [package](https://github.com/walkframe/react-gridsheet) is written in typescript.

It works well in my local environment.

## How has this issue affected you? What are you trying to accomplish?
I cannot get the types in codesandbox.

I published this package v0.2.12 as a different npm package to clarify the cause.
And I tried importing it in the same way, but the type resolution was still failed.
for that reason, I think the causing is not my change.

### To Reproduce
Go the sandbox link, and change the version to 0.2.13 and 0.2.12 in dependencies.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/react-gridsheet-example-simple-dhpok?file=/src/App.tsx

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | create-react-app, React Typescript
| Browser          | Chrome
| Operating System | macOS Catalina

**Comment by joe-sky** [comment]
The same.

Now, all the type definition of packages I published work fine only when Codesandbox install them at the first time. But after switching the package version, it can only run the type definition of the first installed version. 

It's very strange, I remember it worked fine a week ago 😥.

**Comment by Shrugsy** [comment]
I've encountered this same issue with another package on codesandbox: `use-local-slice@1.2.0`. Codesandbox correctly downloads the types on the previous version, but not this one. The issue doesn't occur when installed locally.  

I've reproduced this with `react-gridsheet@0.3.2` also.

### Additional info:
I receive the following CORS errors in the console:
> Access to fetch at 'https://ata.codesandbox.io/api/v8/react-gridsheet%400.3.2.json' from origin 'https://codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Inspecting the network tab, I find that the following url receives a `403` response:  https://prod-packager-packages.codesandbox.io/v1/typings/react-gridsheet/0.3.2.json

Visiting the same url, but swapping out the version for `0.2.12` correctly loads, but versions `0.2.13` and `0.3.2` receive the `403` response.

**Comment by SaraVieira** [comment]
Heyh!

So sorry for the isues, as said this had nothing to do with the code in the sandboxes, there was an issue with our type fetcher that seems to be fixed now :)

Will close but follow if it happens again :)

**Comment by JamesACS** [comment]
Hey @dartandrevinsky, I've just loaded that Sandbox up and I'm not seeing the react-fonts error you've screenshotted above, the error I'm seeing is only the one on the preview pane in your screenshot. 

Does the cannot find module error appear for you on multiple devices/browsers?
